In [20]:
import numpy as np
import math

In [21]:
x = np.array([1,1,1,1,1])
y = [x]

In [22]:
y.append(x)

In [23]:
y[1] - y[0]

array([0, 0, 0, 0, 0])

In [24]:
(y[1] + y[0])**2


array([4, 4, 4, 4, 4])

In [25]:
ex = sum(y) / float(len(y))
print ex

[ 1.  1.  1.  1.  1.]


In [26]:
summ = 0
for i in range (len(y)):
    summ += (ex - y[i])**2
print summ

[ 0.  0.  0.  0.  0.]


In [27]:
-3 % 3

0

In [28]:
print 3 % 3

0


In [29]:
print -3 % 2

1


In [35]:
math.ceil(-3.2)

-3.0

In [36]:
x = 3.2

math.ceil(x)

In [37]:
math.ceil(x)

4.0

In [38]:
x

3.2

In [39]:
str(1+1)

'2'

In [42]:
int("-3"+"0")

-30